# Shortcuts for Greenplum
alias gps='gpstate'
alias gpse='gpstate -e'
alias gpsf='gpstate -f'
#alias gpsshall='gpssh -f ~/gpconfigs/hostfile_all'
#alias gpsshseg='gpssh -f ~/gpconfigs/hostfile_seg'

# Shortcuts for PostgreSQL
#alias pgstrt="pg_ctl start -D $PGDATA"
#alias pgstp="pg_ctl stop -D $PGDATA"


# Shortcuts for PostgreSQL and Greenplum
# Database Locking:
alias blockers='psql -f ~/greenplum/lock_monitoring/blockers_info.sql'
alias waiters='psql -f ~/greemplum/lock_monitoring/waiters_info.sql'
alias locks='psql -f ~/greenplum/lock_monitoring/brief_info.sql'

# Database Activity Monitoring:
alias pgact='psql -f ~/greenplum/database_activity_monitoring/pg_stat.sql'
alias pgactr='psql -f ~/greenplum/database_activity_monitoring/pg_stat_readable.sql'

# Git related shortcuts
alias g="git"
alias gs="git status"
alias ga="git add -A ."                 # Add files in `pwd` to INDEX
alias gst="git st"
alias gps="git push"                    # Update repo with local repo
alias gpl="git pull"                    # Update local repo with remote repo
alias gc="git commit"                   # Commit to HEAD
alias gl="git lg"

# Edit this .bashrc file
alias ebrc='edit ~/.bashrc'

# alias to show the date
alias da='date "+%Y-%m-%d %A %T %Z"'

# Alias's to modified commands
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'
alias ping='ping -c 10'
alias less='less -R'
alias cls='clear'
alias multitail='multitail --no-repeat -c'
alias freshclam='sudo freshclam'
alias vi='vim'
alias svi='sudo vi'

# Change directory aliases
alias home='cd ~'
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# cd into the old directory
alias bd='cd "$OLDPWD"'

# Remove a directory and all files
alias rmd='/bin/rm  --recursive --force --verbose '

# Alias's for multiple directory listing commands
alias la='ls -Alh' # show hidden files
alias lc='ls --color=always' # add colors and file type extensions
alias lx='ls -lXBh' # sort by extension
alias lk='ls -lSrh' # sort by size
alias lc='ls -lcrh' # sort by change time
alias lu='ls -lurh' # sort by access time
alias lr='ls -lRh' # recursive ls
alias lt='ls -ltrh' # sort by date
alias lm='ls -alh |more' # pipe through 'more'
alias lw='ls -xAh' # wide listing format
alias ll='ls -Fls' # long listing format
alias labc='ls -lap' #alphabetical sort
alias lf="ls -l | egrep -v '^d'" # files only
alias ldir="ls -l | egrep '^d'" # directories only

# alias chmod commands
alias mx='chmod a+x'
alias 000='chmod -R 000'
alias 644='chmod -R 644'
alias 666='chmod -R 666'
alias 755='chmod -R 755'
alias 777='chmod -R 777'

# Search command line history
alias h="history | grep "

# Search running processes
alias p="ps aux | grep "
alias topcpu="/bin/ps -eo pcpu,pid,user,args | sort -k 1 -r | head -10"

# Search files in the current folder
alias f="find . | grep "

# Count all files (recursively) in the current folder
alias countfiles="for t in files links directories; do echo \`find . -type \${t:0:1} | wc -l\` \$t; done 2> /dev/null"

# To see if a command is aliased, a file, or a built-in command
alias checkcommand="type -t"

# Show current network connections to the server
alias ipview="netstat -anpl | grep :80 | awk {'print \$5'} | cut -d\":\" -f1 | sort | uniq -c | sort -n | sed -e 's/^ *//' -e 's/ *\$//'"

# Alias's to show disk space and space used in a folder
alias diskspace="du -S | sort -n -r |more"
alias folders='du -h --max-depth=1'
alias folderssort='find . -maxdepth 1 -type d -print0 | xargs -0 du -sk | sort -rn'
alias tree='tree -CAhF --dirsfirst'
alias treed='tree -CAFd'
alias mountedinfo='df -hT'

# Alias's for archives
alias mktar='tar -cvf'
alias untar='tar -xvf'


## SSH Aliases

alias gpadhoc="ssh yjadhav@gpadhoc.db.cnvr.net"
alias gpprod="ssh yjadhav@gpprod.db.cnvr.net"
alias gpmp="ssh yjadhav@gpmp.db.cnvr.net"


## PATH=$PATH:/home2/slitt/apache-maven-3.2.5/bin
alias gpa='sudo -iu gpadmin'
alias dbx='sudo -iu dbxdba'
alias pga='sudo -iu postgres'
alias qw='sudo -iu root'
alias dot='sudo -iu dotomi'
